In [30]:
from urllib.request import Request,urlopen
from requests import get
import pandas as pd
from bs4 import BeautifulSoup
Title=[]
Time=[]
Genre=[]
Certificate=[]
Rating=[]
Votes=[]
Metascore=[]
Collection=[]
url = 'http://www.imdb.com/search/title?release_date=2017&sort=num_votes,desc&page=1'
req=Request(url,headers={'User-Agent': 'Mozilla/5.0'})
response=urlopen(req)


html_soup = BeautifulSoup(response, 'html.parser')
type(html_soup)
movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')

for data in movie_containers:
    vin=data.find_all('h3',{'class':'lister-item-header'})
    for i in vin:
        vik=i.find('a').text
        
        Title.append(vik)
        
for data1 in movie_containers:
    new=data1.find_all('span',{'class':'genre'})
    for i in new:
        Genre.append(i.find(text=True))
        
    new1=data1.find_all('span',{'class':'runtime'})
    for i in new1:
        Time.append(i.find(text=True))
        
        
    new2=data1.find_all('span',{'class':'certificate'})
    for iv in new2:
        vik=iv.find(text=True)
        Certificate.append(vik)
        
    new3=data1.find_all('strong')
    for i in new3:
        Rating.append(float(i.find(text=True)))
        
        
    new4= data1.find_all('span',{'class':'metascore favorable'})
    for i in new4:
        Metascore.append(int(i.find(text=True)))
        
    
    new5=data1.find('span',attrs={'name':'nv'})
    #Votes.append(new5.find(text=True)))
    votes=new5.find(text=True)
    ne=int(votes.replace(',',''))
    Votes.append(ne)
    #here is we use find_all then it the resule also come up with the gross collection but it is not here so try to find out how 
    # to seperapte out it too.
    # form the given data.
    
    for vin in data1:
        
        try:
            new=vin.find_all('span',attrs={'name':'nv'})[1]
            
            Collection.append(new.find(text=True))
            break
                
        except:
            pass
        
#here we try to collect the collection of the movies,
#the collection and the votes are at the same 'span'tag we try to collect the data form both 
#their is A GOOD concept while collecting this data out .
    
    
   
   

    
    
movi_data= %time pd.DataFrame(Title,columns=['Title'])

Wall time: 0 ns

In [22]:
movi_data.head()

                            Title
0                           Logan
1                    Wonder Woman
2  Guardians of the Galaxy Vol. 2
3          Spider-Man: Homecoming
4                         Dunkirk

In [3]:
movi_data['Genre']=Genre
movi_data['Time']=Time
movi_data['Rating']=Rating

In [4]:
#movi_data['Certificate']=pd.Series([1,3,4,5,6,67,7])
#this way it proves to be true but we need to find a new way for the addtion of the certificate series.

In [5]:
movi_data['Certificate']=pd.Series(Certificate)
#as over here we see the certificate already in the form of the list so we don't need to covert it in the form for list.

In [6]:
movi_data['Metascore']=pd.Series(Metascore)

In [7]:
movi_data['Votes']=pd.Series(Votes)

In [8]:
movi_data['Collection']=pd.Series(Collection)

Wall time: 0 ns

,Title,Genre,Time,Rating,Certificate,Metascore,Votes,Collection
0,Logan,"Action, Drama, Sci-Fi",137 min,8.2,A,77.0,412132,$226.28M
1,Wonder Woman,"Action, Adventure, Fantasy",141 min,7.6,PG-13,76.0,336214,$412.56M
2,Guardians of the Galaxy Vol. 2,"Action, Adventure, Sci-Fi",136 min,7.8,PG-13,67.0,300397,$389.81M
3,Spider-Man: Homecoming,"Action, Adventure, Sci-Fi",133 min,7.6,UA,73.0,241803,$334.20M
4,Dunkirk,"Action, Drama, History",106 min,8.3,PG-13,94.0,240767,$188.05M
5,Baby Driver,"Action, Crime, Music",112 min,7.8,R,86.0,220515,$107.83M
6,Get Out,"Horror, Mystery, Thriller",104 min,7.7,R,84.0,205137,$175.48M
7,John Wick: Chapter 2,"Action, Crime, Thriller",122 min,7.6,A,75.0,199329,$92.03M
8,It,"Horror, Thriller",135 min,7.7,A,70.0,184671,$327.35M
9,Beauty and the Beast,"Family, Fantasy, Musical",129 min,7.3,UA,65.0,182196,$504.01M
10,Kong: Skull Island,"Action, Adventure, Fantasy",118 min,6.7,PG-13,62.0,176603,$168.05M
11,Alien: Covenant,"Horror, Sci-Fi, Thriller",122 min,6.5,A,65.0,173826,$74.26M
12,Pirates of the Caribbean: Dead Men Tell No Tales,"Action, Adventure, Fantasy",129 min,6.7,PG-13,73.0,160811,$172.56M
13,Thor: Ragnarok,"Action, Adventure, Comedy",130 min,8.2,UA,81.0,159031,$292.39M
14,Blade Runner 2049,"Mystery, Sci-Fi, Thriller",164 min,8.4,R,82.0,155412,$90.83M
15,The Fate of the Furious,"Action, Adventure, Crime",136 min,6.8,PG-13,75.0,144285,$225.76M
16,13 Reasons Why,"Drama, Mystery",60 min,8.4,R,63.0,139897,$30.23M
17,Life,"Horror, Sci-Fi, Thriller",104 min,6.6,PG-13,67.0,134934,$40.53M
18,Ghost in the Shell,"Action, Crime, Drama",107 min,6.4,PG-13,73.0,132393,$146.88M
19,War for the Planet of the Apes,"Action, Adventure, Drama",140 min,7.5,UA,62.0,132077,$198.55M
20,Justice League,"Action, Adventure, Fantasy",120 min,7.2,PG-13,86.0,127261,$39.18M
21,King Arthur: Legend of the Sword,"Action, Adventure, Drama",126 min,6.9,PG-13,NaN,124824,$80.10M
22,The Mummy,"Action, Adventure, Fantasy",110 min,5.5,R,NaN,112489,$100.06M
23,Kingsman: The Golden Circle,"Action, Adventure, Comedy",141 min,7.1,R,NaN,94591,$75.47M
24,The Hitman's Bodyguard,"Action, Comedy",118 min,7.0,PG,NaN,91110,$175.75M
25,The LEGO Batman Movie,"Animation, Action, Adventure",104 min,7.3,PG-13,NaN,86161,$130.12M
26,Transformers: The Last Knight,"Action, Adventure, Sci-Fi",155 min,5.2,R,NaN,81447,$58.06M
27,Baywatch,"Action, Comedy, Crime",116 min,5.6,R,NaN,80776,$51.57M
28,Atomic Blonde,"Action, Mystery, Thriller",115 min,6.8,PG-13,NaN,77894,$40.48M
29,Valerian and the City of a Thousand Planets,"Action, Adventure, Fantasy",137 min,6.6,PG-13,NaN,74573,$85.07M
30,Taboo,"Drama, Mystery, Thriller",59 min,8.6,R,NaN,73798,$2.40M
31,Iron Fist,"Action, Adventure, Crime",55 min,6.9,R,NaN,72067,$33.80M
32,Power Rangers,"Action, Adventure, Sci-Fi",124 min,6.1,PG-13,NaN,71256,$50.70M
33,Reis,"Biography, Drama",108 min,1.9,PG-13,NaN,70536,$44.90M
34,T2 Trainspotting,Drama,117 min,7.3,PG,NaN,70056,$175.00M
35,Wind River,"Crime, Drama, Mystery",107 min,7.8,R,NaN,68702,$114.38M
36,The Dark Tower,"Action, Adventure, Fantasy",95 min,5.7,R,NaN,65906,$102.09M
37,xXx: Return of Xander Cage,"Action, Adventure, Thriller",107 min,5.2,U,NaN,63383,$264.48M
38,The Boss Baby,"Animation, Comedy, Family",97 min,6.4,PG-13,NaN,62303,$24.80M
39,Fifty Shades Darker,"Drama, Romance",118 min,4.6,UA,NaN,60042,$17.38M
40,Game of Thrones,"Adventure, Drama, Fantasy",50 min,9.8,R,NaN,59819,$42.87M
41,Annabelle: Creation,"Horror, Mystery, Thriller",109 min,6.6,NaN,NaN,56842,NaN
42,Big Little Lies,"Crime, Drama, Mystery",60 min,8.6,NaN,NaN,56674,NaN
43,Despicable Me 3,"Animation, Action, Adventure",90 min,6.3,NaN,NaN,56541,NaN
44,Gifted,Drama,101 min,7.6,NaN,NaN,52254,NaN
45,Bahubali 2: The Conclusion,"Action, Drama, Fantasy",167 min,8.5,NaN,NaN,51639,NaN
46,The Punisher,"Action, Adventure, Crime",685 min,9.0,NaN,NaN,51067,NaN
47,Legion,"Action, Drama, Sci-Fi",60 min,8.5,NaN,NaN,50946,NaN
48,Death Note,"Adventure, Crime, Drama",101 min,4.6,NaN,NaN,50484,NaN
49,The Big Sick,"Comedy, Drama, Romance",120 min,7.7,NaN,NaN,49594,NaN

In [10]:
movi_data.head()
movi_data.dtypes

Title           object
Genre           object
Time            object
Rating         float64
Certificate     object
Metascore      float64
Votes            int64
Collection      object
dtype: object

In [11]:
movi_data.fillna(-99999).head()

,Title,Genre,Time,Rating,Certificate,Metascore,Votes,Collection
0,Logan,"Action, Drama, Sci-Fi",137 min,8.2,A,77.0,412132,$226.28M
1,Wonder Woman,"Action, Adventure, Fantasy",141 min,7.6,PG-13,76.0,336214,$412.56M
2,Guardians of the Galaxy Vol. 2,"Action, Adventure, Sci-Fi",136 min,7.8,PG-13,67.0,300397,$389.81M
3,Spider-Man: Homecoming,"Action, Adventure, Sci-Fi",133 min,7.6,UA,73.0,241803,$334.20M
4,Dunkirk,"Action, Drama, History",106 min,8.3,PG-13,94.0,240767,$188.05M

In [15]:
% time hello=movi_data.drop(['Title','Genre','Time','Collection','Certificate'],1)

Wall time: 0 ns

In [13]:
hello.head()

   Rating  Metascore   Votes
0     8.2       77.0  412132
1     7.6       76.0  336214
2     7.8       67.0  300397
3     7.6       73.0  241803
4     8.3       94.0  240767

In [14]:
import numpy as np
newdata=np.array(hello)
newdata.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [28]:
from urllib.request import urlopen
from bs4 import BeautifulSoup as bs
class ScrapSIC(object):
    def __call__(self):
        page = urlopen('http://www.sec.gov/info/edgar/siccodes.htm')
        soup = bs(page.read(),'lxml')
        table = soup.find_all('table')[2]
        table = table.find('table')
        trs = table.find_all('tr')[3:]
        for tr in trs:
            tds = tr.find_all('td')
            sic_code = tds[0].string
            sic_name = tds[-1].string.title()
            print(sic_code, sic_name)
s=%time ScrapSIC()

Wall time: 0 ns